### ISSUE TITLE
py3 compatibility

### ISSUE THREAD

**Issue by Kwpolska** [getnikola/comet_cms#37]
http://pastebin.com/gVrcas9q

**Comment by gour** [comment]
``` pytb
Traceback (most recent call last):
  File "/home/gour/prj/nikola/lib/python3.4/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/gour/prj/nikola/lib/python3.4/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/gour/prj/nikola/lib/python3.4/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/gour/prj/nikola/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/gour/prj/nikola/lib/python3.4/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/gour/prj/nikola/lib/python3.4/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/gour/prj/nikola/lib/python3.4/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/gour/prj/nikola/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/gour/prj/nikola/lib/python3.4/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/gour/prj/nikola/lib/python3.4/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/gour/prj/nikola/lib/python3.4/site-packages/coil/web.py", line 530, in login
    request.form['password'])
  File "/home/gour/prj/nikola/lib/python3.4/site-packages/coil/web.py", line 223, in check_password
    return bcrypt_sha256.verify(password, pwdhash)
  File "/home/gour/prj/nikola/lib/python3.4/site-packages/passlib/utils/handlers.py", line 571, in verify
    return consteq(self._calc_checksum(secret), chk)
  File "/home/gour/prj/nikola/lib/python3.4/site-packages/passlib/handlers/bcrypt.py", line 447, in _calc_checksum
    return self._calc_checksum_backend(key)
  File "/home/gour/prj/nikola/lib/python3.4/site-packages/passlib/utils/handlers.py", line 1458, in _calc_checksum_backend
    return self._calc_checksum_backend(secret)
  File "/home/gour/prj/nikola/lib/python3.4/site-packages/passlib/handlers/bcrypt.py", line 333, in _calc_checksum_pybcrypt
    hash = _bcrypt.hashpw(secret, config)
TypeError: hashpw() argument 1 must be str, not bytes
```
